---
name: Create Release

permissions:
  contents: write # For release-please (create PR, release, tag)
  pull-requests: write # For release-please (create PR)

on:
  push:
    branches: ["main"]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Secure runner
        uses: step-security/harden-runner@v2.11.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            storage.googleapis.com:443

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Define release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.AUTO_RELEASE_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
